index:
    path: /
    controller: App\Controller\DefaultController::index

buscarlibros:
    path: /buscarlibros
    controller: App\Controller\DefaultController::buscarLibros

guardarlibro:
    path: /guardarlibro
    controller: App\Controller\DefaultController::guardarLibros

eliminarlibro:
    path: /eliminarlibro
    controller: App\Controller\DefaultController::eliminarLibro

buscarautoresrelacionados:
    path: /buscarautoresrelacionados
    controller: App\Controller\DefaultController::buscarAutoresRelacionados

eliminarautorrelacionado:
    path: /eliminarautorrelacionado
    controller: App\Controller\DefaultController::eliminarAutorRelacionado

guardarautoresrelacionados:
    path: /guardarautoresrelacionados
    controller: App\Controller\DefaultController::guardarAutorRelacionado

buscarautores:
    path: /buscarautores
    controller: App\Controller\DefaultController::buscarAutores

guardarautor:
    path: /guardarautor
    controller: App\Controller\DefaultController::guardarAutor

eliminarautor:
    path: /eliminarautor
    controller: App\Controller\DefaultController::eliminarAutor

guardareditorial:
    path: /guardareditorial
    controller: App\Controller\DefaultController::guardarEditorial

buscareditorial:
    path: /buscareditorial
    controller: App\Controller\DefaultController::buscarEditoriales

eliminareditorial:
    path: /eliminareditorial
    controller: App\Controller\DefaultController::eliminarEditorial
