index:
    path: /
    controller: App\Controller\DefaultController::index

buscarautores:
    path: /buscarautores
    controller: App\Controller\DefaultController::buscarAutores

guardarautor:
    path: /guardarautor
    controller: App\Controller\DefaultController::guardarAutor

eliminarautor:
    path: /eliminarautor
    controller: App\Controller\DefaultController::eliminarAutor

guardareditorial:
    path: /guardareditorial
    controller: App\Controller\DefaultController::guardarEditorial

buscareditorial:
    path: /buscareditorial
    controller: App\Controller\DefaultController::buscarEditoriales

eliminareditorial:
    path: /eliminareditorial
    controller: App\Controller\DefaultController::eliminarEditorial
